# This is a basic workflow to help you get started with Actions
name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
   
    - name: build-web
      run: |
        npm install
        npm run build-web
        
    - name: GitHub Pages Deploy
      uses: appleboy/gh-pages-action@v0.0.2
      
    - name: deploy pages
      uses: ./
      with:
        target_branch: gh-pages
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        remote_url: https://github.com/ucsd-cse231-w21/chocopy-wasm-compiler.git
        pages_directory: build



